name: Trigger Jenkins Job

on:
  push:
    branches:
      - main

jobs:
  trigger:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger Jenkins build
        run: |
          curl -u "${{ secrets.JENKINS_USER }}:${{ secrets.JENKINS_API_TOKEN }}" \
               -X POST "${{ secrets.JENKINS_URL }}/job/node_pipeline/build?token=github_token"
